name: Run Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run cmake and make
      run: |
        cd tests
        mkdir build && cd build
        cmake ..
        make
        ./PJTest
