[package]
name = "trojan"
version = "0.15.0"
authors = ["Hoping White <baihaoping@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive", "cargo", "env"] }
mio = { version = "0.8", features = ["net", "os-poll"] }
log = "0.4"
chrono = "0.4"
libc = "0.2"
rustls = "0.21"
sha2 = "0.10"
bytes = "1.2"
dns-lookup = "2.0"
cfg-if = "1.0"
webpki-roots = "0.23"
webpki = "0.22"
socket2 = "0.5"
rayon = "1.5"
rustls-pemfile = "1.0"
lazy_static = "1.4"
derive_more = "0.99"
libloading = "0.7"
crossbeam = "0.8"
trust-dns-proto = "0.22"
widestring = "1.0"
itertools = "0.10"
smoltcp = { version = "0.10" }
backtrace = "0.3"
hex = "0.4"
surge-ping = "0.8"
tokio = { version = "1.29", features = ["full"] }
rand = "0.8"
test-log = "0.2"
notify = "6.0"
ringbuf = "0.3"
httparse = "1.8"
tokio_rustls = { path = "tokio_rustls" }
async_smoltcp = { path = "async_smoltcp" }

[dev-dependencies]
env_logger = "0.10"

[target.'cfg(windows)'.dependencies]
wintun = "0.2"
wintool = { path = "wintool" }
winapi = { version = "0.3", features = ["netioapi", "impl-debug", "impl-default", "combaseapi", "ipifcons"] }

[target.'cfg(not(windows))'.dependencies]
backtrace-on-stack-overflow = "0.3"
ipset = { version = "0.4" }

[dependencies.fern]
version = "0.6"
features = ["reopen-03"]

[profile.release]
lto = true
