version: "3"
services:
  v2raya:
    privileged: true
    network_mode: host # --network host
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./service:/service:ro
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf
