name: "Docker"

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: "Docker Hub"
    strategy:
      matrix:
        variant: ["client", "server"]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - # TODO: port https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile.${{ matrix.variant }}
          tags: m13253/dns-over-https-${{ matrix.variant }}:latest
          push: true
          platforms: "linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8"
