name: build

on:
  push:
    push:
      branches:
        - master
      tags:
        - v*
        - latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: v0.4.1

      - name: update submodules
        run: git submodule update --init

      - name: login docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: build edge image
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx build \
            --push \
            --platform=linux/arm64,linux/amd64 \
            -f=docker/alpine/Dockerfile \
            -t=${{ github.repository }}:edge \
            .
      - name: build version image
        if: github.ref != 'refs/heads/master'
        run: |
          docker buildx build \
            --push \
            --platform=linux/arm64,linux/amd64 \
            -f=docker/alpine/Dockerfile \
            -t=${{ github.repository }}:$(echo ${{ github.ref }} | sed -E 's|refs/tags/||') \
            .