name: build

on: [push, pull_request]

jobs:

  linux:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [
            g++-7, g++-8, g++-9, g++,
            clang++-8, clang++-9, clang++-10, clang++
        ]
        mode: [-DBUILD_UVW_SHARED_LIB=ON, -DBUILD_UVW_LIBS=ON, -DBUILD_UVW_LIBS=OFF]

    steps:
    - uses: actions/checkout@v2
    - name: Install g++-7
      if: ${{ matrix.compiler == 'g++-7' }}
      run: |
        sudo apt-get update
        sudo apt-get install g++-7 -y
    - name: Install g++-8
      if: ${{ matrix.compiler == 'g++-8' }}
      run: |
        sudo apt-get update
        sudo apt-get install g++-8 -y
    - name: Install clang-8
      if: ${{ matrix.compiler == 'clang++-8' }}
      run: |
        sudo apt-get update
        sudo apt-get install clang-8 -y
    - name: Install clang-9
      if: ${{ matrix.compiler == 'clang++-9' }}
      run: |
        sudo apt-get update
        sudo apt-get install clang-9 -y
    - name: Install clang-10
      if: ${{ matrix.compiler == 'clang++-10' }}
      run: |
        sudo apt-get update
        sudo apt-get install clang-10 -y
    - name: Compile tests
      working-directory: build
      env:
        CXX: ${{ matrix.compiler }}
      run: |
        cmake ${{ matrix.mode }} -DBUILD_TESTING=ON -Dlibuv_buildtests=OFF ..
        make -j2
    - name: Run tests
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --timeout 5 -C Debug -j2

  windows:
    timeout-minutes: 60
    runs-on: windows-latest

    strategy:
      matrix:
        generator: [Visual Studio 17 2022]
        mode: [-DBUILD_UVW_SHARED_LIB=ON, -DBUILD_UVW_LIBS=ON, -DBUILD_UVW_LIBS=OFF]

    steps:
    - uses: actions/checkout@v1
    - name: Compile tests
      working-directory: build
      run: |
        cmake -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE ${{ matrix.mode }} -DBUILD_TESTING=ON -Dlibuv_buildtests=OFF -DCMAKE_CXX_FLAGS=/W1 -G"${{ matrix.generator }}" ..
        cmake --build . -j 2

  macos:
    timeout-minutes: 60
    runs-on: macOS-latest

    strategy:
      matrix:
        mode: [-DBUILD_UVW_SHARED_LIB=ON, -DBUILD_UVW_LIBS=ON, -DBUILD_UVW_LIBS=OFF]

    steps:
    - uses: actions/checkout@v1
    - name: Compile tests
      working-directory: build
      run: |
        cmake ${{ matrix.mode }} -DBUILD_TESTING=ON -Dlibuv_buildtests=OFF ..
        make -j2
