global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
scrape_configs:
  - job_name: "relay_nodes"
    scrape_interval: "30s"
    metrics_path: "/metrics/"
    static_configs:
      - targets:
          - 127.0.0.1:9000
