language: shell
os: linux
dist: bionic

script:
  - echo Refreshing launchpad repository

deploy:
  - provider: launchpad
    slug: "~ymshenyu/qv2ray/+git/trunk"
    oauth_token: $LAUNCHPAD_OAUTH_TOKEN
    oauth_token_secret: $LAUNCHPAD_OAUTH_TOKEN_SECRET
    on:
      all_branches: true