[package]
name = "tokio_rustls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.29", features = ["net", "sync"] }
rustls = "0.21"
log = "0.4"
bytes = "1.4"