name: v2raya-nightly-docker

on:
  push:
    branches: [ feat_v5 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        id: prep
        run: |
          TAG=$(git log --pretty=format:"%ad" --date=format:%Y%m%d $(git show -s --format=%H) -1)
          IMAGE="mzz2017/v2raya-nightly"
          echo image=${IMAGE} >> $GITHUB_OUTPUT
          echo tag=${TAG} >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
      - name: Build production image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile.nightly
          platforms: linux/arm,linux/arm64,linux/amd64
          push: true
          tags: |
            ${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.tag }}
            ${{ steps.prep.outputs.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
