name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    
