language: go
sudo: false
go:
  - 1.x

install: true
script:
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic
  - cd cmd/gost && go build

after_success:
  - bash <(curl -s https://codecov.io/bash)
