name: "Build master"

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - 'v*'
      - 'core/v*'
      - 'app/v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:

      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Run build script
        env:
          HY_APP_PLATFORMS: 'darwin/amd64,darwin/amd64-avx,darwin/arm64,windows/amd64,windows/amd64-avx,windows/386,windows/arm64,linux/amd64,linux/amd64-avx,linux/386,linux/arm,linux/armv5,linux/arm64,linux/s390x,linux/mipsle,linux/mipsle-sf,freebsd/amd64,freebsd/amd64-avx,freebsd/386,freebsd/arm,freebsd/arm64'
        run: ./build.sh
        shell: bash

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: hysteria-binaries-${{ github.sha }}
          path: ./build
