# By default, SwiftLint uses a set of sensible default rules you can adjust:
disabled_rules: # rule identifiers turned on by default to exclude from running
  - colon
  - identifier_name
  - force_cast
  - closure_parameter_position
  - file_length
  - large_tuple
  - type_body_length
  - cyclomatic_complexity
  - function_body_length
  - nesting
opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - empty_count
  - empty_string
included: # paths to include during linting. `--path` is ignored if present.
  - ClashX
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - ClashX/Vendor
  - Pods
analyzer_rules: # Rules run by `swiftlint analyze`
  - explicit_self
# implicitly
line_length: 300
# reporter: "xcode"
